// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SatinAlmaStokTakip.Models;

#nullable disable

namespace SatinAlmaStokTakip.Migrations
{
    [DbContext(typeof(VeritabaniContext))]
    partial class VeritabaniContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Bildirim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Baslik")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<string>("Mesaj")
                        .HasColumnType("longtext");

                    b.Property<bool>("Okundu")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tip")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Fatura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FaturaNo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FaturaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TeklifID")
                        .HasColumnType("int");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ID");

                    b.HasIndex("TeklifID");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Kullanici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .HasColumnType("longtext");

                    b.Property<string>("Sifre")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Log", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Islem")
                        .HasColumnType("longtext");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Loglar");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Stok", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MalzemeAdi")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Stoklar");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Talep", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("longtext");

                    b.Property<string>("Durum")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("OnayDurumu")
                        .HasColumnType("longtext");

                    b.Property<string>("OnayNotu")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OnaylayanKullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("OnaylayanKullaniciID");

                    b.ToTable("Talepler");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Teklif", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("longtext");

                    b.Property<string>("FirmaAdi")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notlar")
                        .HasColumnType("longtext");

                    b.Property<string>("OnayDurumu")
                        .HasColumnType("longtext");

                    b.Property<string>("OnayNotu")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OnaylayanKullaniciID")
                        .HasColumnType("int");

                    b.Property<int>("TalepID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OnaylayanKullaniciID");

                    b.HasIndex("TalepID");

                    b.ToTable("Teklifler");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Tuketim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int>("StokID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("StokID");

                    b.ToTable("Tuketimler");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Yorum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Icerik")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KayitID")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int?>("TalepID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TeklifID")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("TalepID");

                    b.HasIndex("TeklifID");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Bildirim", b =>
                {
                    b.HasOne("SatinAlmaStokTakip.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Fatura", b =>
                {
                    b.HasOne("SatinAlmaStokTakip.Models.Teklif", "Teklif")
                        .WithMany()
                        .HasForeignKey("TeklifID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teklif");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Talep", b =>
                {
                    b.HasOne("SatinAlmaStokTakip.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatinAlmaStokTakip.Models.Kullanici", "OnaylayanKullanici")
                        .WithMany()
                        .HasForeignKey("OnaylayanKullaniciID");

                    b.Navigation("Kullanici");

                    b.Navigation("OnaylayanKullanici");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Teklif", b =>
                {
                    b.HasOne("SatinAlmaStokTakip.Models.Kullanici", "OnaylayanKullanici")
                        .WithMany()
                        .HasForeignKey("OnaylayanKullaniciID");

                    b.HasOne("SatinAlmaStokTakip.Models.Talep", "Talep")
                        .WithMany("Teklifler")
                        .HasForeignKey("TalepID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnaylayanKullanici");

                    b.Navigation("Talep");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Tuketim", b =>
                {
                    b.HasOne("SatinAlmaStokTakip.Models.Stok", "Stok")
                        .WithMany()
                        .HasForeignKey("StokID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stok");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Yorum", b =>
                {
                    b.HasOne("SatinAlmaStokTakip.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatinAlmaStokTakip.Models.Talep", null)
                        .WithMany("Yorumlar")
                        .HasForeignKey("TalepID");

                    b.HasOne("SatinAlmaStokTakip.Models.Teklif", null)
                        .WithMany("Yorumlar")
                        .HasForeignKey("TeklifID");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Talep", b =>
                {
                    b.Navigation("Teklifler");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("SatinAlmaStokTakip.Models.Teklif", b =>
                {
                    b.Navigation("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
